version: "3.7"

services:
  cleaning-app:
    container_name: cleaning-app
    restart: always
    build:
      context: .
      dockerfile: dockerfiles/app/Dockerfile
    command: run
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    env_file:
      - .env
    ports:
      - 127.0.0.1:8000:8000
    links:
      - db
    depends_on:
      - db
      - redis

  huey:
    container_name: cleaning-huey
    restart: always
    build:
      context: .
      dockerfile: dockerfiles/app/Dockerfile
    command: run_worker
    env_file:
      - .env
    depends_on:
      - cleaning-app

  db:
    container_name: cleaning-db
    restart: always
    image: postgres:12.4-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      - .env
    expose:
      - 5432

  redis:
    container_name: cleaning-redis
    restart: always
    image: redis:6.0.9-alpine
    expose:
      - 6379

volumes:
  postgres-data:
