# Generated by Django 3.2 on 2021-04-13 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_auto_20210413_1515'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('phone_number', models.CharField(max_length=10, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=255, verbose_name='Улица и Номер дома')),
                ('date', models.DateTimeField(verbose_name='Дата и время бронирования')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания заказа')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления бро')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Компания исполнитель')),
                ('locality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.locality', verbose_name='Город назначения')),
                ('performer_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employee', verbose_name='Сотрудник исполнитель')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['created'],
            },
        ),
    ]
