# Generated by Django 3.2 on 2021-04-15 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcalendar',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.booking', verbose_name='Бронь'),
        ),
        migrations.AddField(
            model_name='eventcalendar',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounts.employee', verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to=settings.AUTH_USER_MODEL, verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='activity_localities',
            field=models.ManyToManyField(to='services.Locality', verbose_name='Населенные пункты деятельности'),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='companyuser',
            unique_together={('email', 'company_name')},
        ),
    ]
