# Generated by Django 3.2 on 2021-04-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='activity_localities',
            field=models.ManyToManyField(to='services.Locality', verbose_name='Населенные пункты деятельности'),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='employees',
            field=models.ManyToManyField(to='accounts.Employee', verbose_name='Сотрудники'),
        ),
    ]
