# Generated by Django 3.2 on 2021-04-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210412_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='phone_number',
            field=models.CharField(max_length=10, null=True, verbose_name='Номер телефона'),
        ),
    ]
