# Generated by Django 3.2 on 2021-04-22 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_eventcalendar_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyuser',
            name='username',
        ),
    ]
