# Generated by Django 3.2 on 2021-04-13 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_companyuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyuser',
            name='employees',
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to=settings.AUTH_USER_MODEL, verbose_name='Компания'),
        ),
    ]
